# 05 - Array Manipulation

## Introduction

Array manipulation involves changing the shape, size, or structure of arrays. This is essential for data preprocessing, feature engineering, and preparing data for machine learning models.

## What You'll Learn

- Reshaping arrays
- Flattening arrays
- Transposing arrays
- Stacking arrays (vstack, hstack, concatenate)
- Splitting arrays
- Adding/removing dimensions


In [2]:
import numpy as np


## Reshaping Arrays

Reshaping changes the dimensions of an array without changing its data. The total number of elements must remain the same.


In [2]:
# Create a 1D array
arr = np.arange(12)
print("Original 1D array:", arr)

# Reshape to 2D
arr_2d = arr.reshape(3, 4)
print("\nReshaped to 3x4:")
print(arr_2d)

# Reshape to 3D
arr_3d = arr.reshape(2, 3, 2)
print("\nReshaped to 2x3x2:")
print(arr_3d)

# Using -1 for automatic dimension
arr_auto = arr.reshape(3, -1)  # -1 means "calculate automatically"
print("\nReshaped with -1 (3x4):")
print(arr_auto)


Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 2x3x2:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

Reshaped with -1 (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Flattening Arrays

Flattening converts multi-dimensional arrays to 1D.


In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:")
print(arr2d)

# Flatten (returns a copy)
flattened = arr2d.flatten()
print(f"\nFlattened: {flattened}")

# Ravel (returns a view when possible)
raveled = arr2d.ravel()
print(f"Raveled: {raveled}")


2D array:
[[1 2 3]
 [4 5 6]]

Flattened: [1 2 3 4 5 6]
Raveled: [1 2 3 4 5 6]


## Transposing Arrays

Transposing swaps rows and columns.


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:")
print(arr)
print(f"Shape: {arr.shape}")

# Transpose
transposed = arr.T
print("\nTransposed:")
print(transposed)
print(f"Shape: {transposed.shape}")


Original:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transposed:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


## Stacking Arrays

Stacking combines multiple arrays into one.


In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stack (stack along axis 0)
vstacked = np.vstack([a, b])
print("Vertical stack:")
print(vstacked)

# Horizontal stack (stack along axis 1)
hstacked = np.hstack([a, b])
print(f"\nHorizontal stack: {hstacked}")

# Concatenate (more general)
concatenated = np.concatenate([a, b])
print(f"Concatenated: {concatenated}")


Vertical stack:
[[1 2 3]
 [4 5 6]]

Horizontal stack: [1 2 3 4 5 6]
Concatenated: [1 2 3 4 5 6]


## Summary

In this notebook, you learned:

1. **Reshaping**: Changing array dimensions with reshape()
2. **Flattening**: Converting to 1D with flatten() or ravel()
3. **Transposing**: Swapping dimensions with .T
4. **Stacking**: Combining arrays with vstack, hstack, concatenate

**Key Takeaways**:
- Reshape requires same total number of elements
- Flatten creates copy, ravel creates view when possible
- Transpose is essential for matrix operations
- Stacking is useful for combining datasets

**Next Steps**: In the next notebook, we'll learn about broadcasting - a powerful feature for operations on arrays of different shapes.
