# 06 - Broadcasting

## Introduction

Broadcasting is a powerful NumPy feature that allows operations on arrays of different shapes. It eliminates the need for explicit loops and makes code more efficient and readable.

## What You'll Learn

- Understanding broadcasting rules
- Broadcasting examples
- When broadcasting works and when it doesn't
- Practical broadcasting scenarios


In [1]:
import numpy as np


In [2]:
# Example 1: Array + Scalar
def add_column(arr,col):
    return (arr+col)


arr = np.array([[1, 2, 3], [4, 5, 6]])
col = np.array([[10], [20]])  # Column vector
print(f"\nArray + Column:")
print(add_column(arr,col)) 




Array + Column:
[[11 12 13]
 [24 25 26]]


## What is Broadcasting?

Broadcasting allows NumPy to perform operations on arrays of different shapes. The smaller array is "broadcast" across the larger array so they have compatible shapes.

**Broadcasting Rules:**
1. Arrays are aligned from the right
2. Dimensions are compatible if they're equal or one is 1
3. Arrays can be broadcast if trailing dimensions match


In [ ]:
# Example 1: Array + Scalar
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:")
print(arr)
print(f"\nArray + 10:")
print(arr + 10)  # Scalar is broadcast to match array shape


Array:
[[1 2 3]
 [4 5 6]]

Array + 10:
[[11 12 13]
 [14 15 16]]


In [ ]:
# Example 2: Array + 1D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
row = np.array([10, 20, 30])
print("Array:")
print(arr)
print(f"\nRow to add: {row}")
print(f"\nArray + Row:")
print(arr + row)  # Row is broadcast to each row of the array


Array:
[[1 2 3]
 [4 5 6]]

Row to add: [10 20 30]

Array + Row:
[[11 22 33]
 [14 25 36]]


In [ ]:
# Example 3: Column broadcasting
arr = np.array([[1, 2, 3], [4, 5, 6]])
col = np.array([[10], [20]])  # Column vector
print("Array:")
print(arr)
print(f"\nColumn to add:")
print(col)
print(f"\nArray + Column:")
print(arr + col)  # Column is broadcast to each column


Array:
[[1 2 3]
 [4 5 6]]

Column to add:
[[10]
 [20]]

Array + Column:
[[11 12 13]
 [24 25 26]]


In [ ]:
print("Hello")

## Summary

In this notebook, you learned:

1. **Broadcasting concept**: Operations on arrays of different shapes
2. **Broadcasting rules**: How NumPy determines compatibility
3. **Practical examples**: Scalar, row, and column broadcasting

**Key Takeaways**:
- Broadcasting eliminates need for explicit loops
- Makes code more readable and efficient
- Essential for data preprocessing and feature engineering
- Understanding shapes is crucial for broadcasting

**Next Steps**: In the next notebook, we'll learn about linear algebra operations.
