# 07 - Linear Algebra

## Introduction

Linear algebra is fundamental for data engineering, machine learning, and data transformations. NumPy provides comprehensive linear algebra functions through the `linalg` module.

## What You'll Learn

- Matrix multiplication
- Dot product
- Vector operations
- Matrix operations (transpose, inverse, determinant)
- Solving linear equations


In [ ]:
import numpy as np


## Dot Product and Matrix Multiplication

### Dot Product

The **dot product** (also called scalar product) of two vectors **a** and **b** is defined as:

$$\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^{n} a_i b_i = a_1 b_1 + a_2 b_2 + \ldots + a_n b_n$$

For vectors **a** = [a₁, a₂, ..., aₙ] and **b** = [b₁, b₂, ..., bₙ], the dot product is:

$$\mathbf{a} \cdot \mathbf{b} = a_1 b_1 + a_2 b_2 + \ldots + a_n b_n$$

**Properties:**
- The result is a scalar (single number)
- Commutative: **a** · **b** = **b** · **a**
- Distributive: **a** · (**b** + **c**) = **a** · **b** + **a** · **c**

### Matrix Multiplication

For two matrices **A** (m × n) and **B** (n × p), the matrix product **C** = **AB** is defined as:

$$C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}$$

Where:
- **C** has dimensions (m × p)
- Element Cᵢⱼ is the dot product of row i of **A** and column j of **B**

**Important:** Matrix multiplication is **not commutative**: **AB** ≠ **BA** (in general)


In [ ]:
# Dot product of vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print(f"Vectors: a={a}, b={b}")
print(f"Dot product: {dot_product}")

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(f"\nMatrix A:\n{A}")
print(f"\nMatrix B:\n{B}")
print(f"\nA @ B (matrix multiplication):\n{result}")

# Using @ operator (Python 3.5+)
result2 = A @ B
print(f"\nUsing @ operator:\n{result2}")


Vectors: a=[1 2 3], b=[4 5 6]
Dot product: 32

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A @ B (matrix multiplication):
[[19 22]
 [43 50]]

Using @ operator:
[[19 22]
 [43 50]]


## Matrix Operations

### Matrix Transpose

The **transpose** of a matrix **A**, denoted as **A**ᵀ or **A**', is obtained by flipping the matrix over its diagonal:

$$(A^T)_{ij} = A_{ji}$$

If **A** is an m × n matrix, then **A**ᵀ is an n × m matrix.

**Properties:**
- (**A**ᵀ)ᵀ = **A**
- (**AB**)ᵀ = **B**ᵀ**A**ᵀ
- (**A** + **B**)ᵀ = **A**ᵀ + **B**ᵀ

### Matrix Inverse

The **inverse** of a square matrix **A**, denoted as **A**⁻¹, is a matrix such that:

$$\mathbf{A} \mathbf{A}^{-1} = \mathbf{A}^{-1} \mathbf{A} = \mathbf{I}$$

Where **I** is the identity matrix.

**Important:**
- Only square matrices can have inverses
- Not all square matrices are invertible (determinant must be non-zero)
- If det(**A**) = 0, the matrix is **singular** (non-invertible)

For a 2×2 matrix:

$$\mathbf{A} = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$$

The inverse is:

$$\mathbf{A}^{-1} = \frac{1}{ad - bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix} = \frac{1}{\det(\mathbf{A})} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$

### Determinant

The **determinant** of a square matrix **A**, denoted as det(**A**) or |**A**|, is a scalar value.

For a 2×2 matrix:

$$\mathbf{A} = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$$

The determinant is:

$$\det(\mathbf{A}) = ad - bc$$

**Properties:**
- If det(**A**) = 0, the matrix is singular (non-invertible)
- If det(**A**) ≠ 0, the matrix is invertible
- det(**AB**) = det(**A**) × det(**B**)
- det(**A**ᵀ) = det(**A**)

**Geometric Interpretation:** The absolute value of the determinant represents the scaling factor of the linear transformation represented by the matrix.


In [3]:
# Matrix transpose
A = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix A:")
print(A)
print(f"\nTranspose A.T:\n{A.T}")

# Matrix inverse (for square matrices)
A_square = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A_square)
print(f"\nMatrix:\n{A_square}")
print(f"\nInverse:\n{A_inv}")
print(f"\nA @ A_inv (should be identity):\n{A_square @ A_inv}")

# Determinant
det = np.linalg.det(A_square)
print(f"\nDeterminant: {det}")


Matrix A:
[[1 2 3]
 [4 5 6]]

Transpose A.T:
[[1 4]
 [2 5]
 [3 6]]

Matrix:
[[1 2]
 [3 4]]

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv (should be identity):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Determinant: -2.0000000000000004


## Solving Linear Equations

A system of linear equations can be written in matrix form as:

$$\mathbf{A}\mathbf{x} = \mathbf{b}$$

Where:
- **A** is the coefficient matrix (n × n)
- **x** is the vector of unknowns (n × 1)
- **b** is the constant vector (n × 1)

If **A** is invertible, the solution is:

$$\mathbf{x} = \mathbf{A}^{-1}\mathbf{b}$$

**Example:** Solve the system:
- 2x + y = 5
- x - y = 1

In matrix form:
$$\begin{bmatrix} 2 & 1 \\ 1 & -1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 5 \\ 1 \end{bmatrix}$$


In [4]:
# Solving linear equations: Ax = b
# Example: 2x + y = 5, x - y = 1

A = np.array([[2, 1], [1, -1]])  # Coefficient matrix
b = np.array([5, 1])              # Constant vector

# Method 1: Using inverse (x = A^(-1) * b)
x1 = np.linalg.inv(A) @ b
print("Solution using inverse:")
print(f"x = {x1[0]:.2f}, y = {x1[1]:.2f}")

# Method 2: Using solve() (more efficient and numerically stable)
x2 = np.linalg.solve(A, b)
print(f"\nSolution using solve():")
print(f"x = {x2[0]:.2f}, y = {x2[1]:.2f}")

# Verify the solution
print(f"\nVerification (Ax should equal b):")
print(f"A @ x = {A @ x2}")
print(f"b = {b}")


Solution using inverse:
x = 2.00, y = 1.00

Solution using solve():
x = 2.00, y = 1.00

Verification (Ax should equal b):
A @ x = [5. 1.]
b = [5 1]


## Summary

In this notebook, you learned:

1. **Dot product**: Mathematical formula and vector multiplication
2. **Matrix multiplication**: Formula and element-wise computation
3. **Matrix transpose**: Definition and properties
4. **Matrix inverse**: Formula for 2×2 matrices and invertibility conditions
5. **Determinant**: Formula for 2×2 matrices and geometric interpretation
6. **Solving linear equations**: Using matrix inverse and `np.linalg.solve()`

**Key Takeaways**:
- Dot product: **a** · **b** = Σ aᵢbᵢ (scalar result)
- Matrix multiplication: Cᵢⱼ = Σ AᵢₖBₖⱼ (not commutative)
- Transpose: (Aᵀ)ᵢⱼ = Aⱼᵢ (flip over diagonal)
- Inverse: **A**⁻¹ exists only if det(**A**) ≠ 0
- Determinant: For 2×2, det = ad - bc (determines invertibility)
- Linear equations: **x** = **A**⁻¹**b** or use `np.linalg.solve()`

**Mathematical Foundation**: These operations are fundamental for:
- Data transformations and rotations
- Machine learning algorithms (neural networks, PCA, etc.)
- Solving systems of equations
- Understanding geometric transformations

**Next Steps**: In the next notebook, we'll work through a practical data engineering example using all NumPy concepts.
