# 09 - NumPy Exercises

## Introduction

Practice makes perfect! This notebook contains exercises to reinforce what you've learned. Try to solve each exercise before looking at solutions.

## Instructions

1. Read each exercise carefully
2. Write your solution in the code cell
3. Run your code to verify it works
4. Compare with the solution in the next notebook


In [1]:
import numpy as np


## Exercise 1: Array Creation

Create the following arrays:
1. An array of zeros with shape (3, 4)
2. An array of ones with shape (2, 5)
3. An array with values from 0 to 9
4. An array with 10 evenly spaced values from 0 to 1
5. A 3x3 identity matrix


In [ ]:
# Your solution here
#1
print(np.zeros((3,4)))
#2
print(np.ones((2,5)))
#3
print(np.arange(10))
#4
print(np.linspace(0,1,10))
#5
print(np.identity(3))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Exercise 2: Array Operations

Given the array: `arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])`

1. Select elements greater than 40
2. Select elements between 30 and 60 (inclusive)
3. Select elements at indices 0, 2, 4, 6
4. Reverse the array


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

#1
print(arr[arr>40])

#2
print((arr[(arr>30) & (arr<60)]))

#3
indices = np.array([0,2,4,6])
print(f"element at indices {indices} is {arr[indices]}")

#4
reversed_array = arr[::-1]
print(reversed_array)


[50 60 70 80]
[40 50]
element at indices [0 2 4 6] is [10 30 50 70]
[80 70 60 50 40 30 20 10]


## Exercise 3: Mathematical Operations

Given: `a = np.array([1, 2, 3, 4, 5])` and `b = np.array([10, 20, 30, 40, 50])`

1. Calculate element-wise sum, difference, product
2. Calculate mean, std, min, max of array a
3. Calculate sum along axis for a 2D array: `arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`


In [19]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#1
print("Sum is ",a+b)
print(f"difference is {a-b}")
print(f"product is {a*b}")

#2
print(f"mean {np.mean(a)}")
print(f"std {np.std(a)}")
print(f"min {np.min(a)}")
print(f"max {np.max(a)}")

#3
print(f"sum along with axis is {np.sum(arr2d,axis=1)}")


Sum is  [11 22 33 44 55]
difference is [ -9 -18 -27 -36 -45]
product is [ 10  40  90 160 250]
mean 3.0
std 1.4142135623730951
min 1
max 5
sum along with axis is [ 6 15 24]


## Exercise 4: Array Manipulation

1. Reshape array `np.arange(12)` to shape (3, 4)
2. Flatten a 2D array `np.array([[1, 2, 3], [4, 5, 6]])`
3. Transpose the array from step 1
4. Stack two arrays `a = np.array([1, 2, 3])` and `b = np.array([4, 5, 6])` vertically


In [26]:
# Your solution here
#1
reshaped_array = np.arange(12).reshape(3,4)
print(reshaped_array)

#2
print(np.array([[1,2,3],[4,5,6]]).flatten())

#3
transpose = reshaped_array.T
print(transpose)

#4
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstacked = np.vstack([a,b])
print(vstacked)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3 4 5 6]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[1 2 3]
 [4 5 6]]


## Exercise 5: Data Processing

Given sensor data: `data = np.random.normal(25, 5, (10, 3))` (10 days, 3 sensors)

1. Calculate mean temperature for each sensor
2. Find the day with the highest average temperature
3. Normalize the data using Z-score
4. Calculate correlation between sensors


In [30]:
np.random.seed(42)
data = np.random.normal(25, 5, (10, 3))


#1
sensor_mean = np.mean(data, axis=0)
print("\nMean temperature for each sensor:", sensor_mean)

#2
daily_avg = np.mean(data, axis=1)
max_day_index = np.argmax(daily_avg)
print("\nDay with highest average temperature:", max_day_index + 1)

#3
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

zscore_data = (data - mean) / std
print("\nZ-score normalized data:\n", zscore_data)

#4
correlation = np.corrcoef(data, rowvar=False)
print("\nCorrelation between sensors:\n", correlation)






Mean temperature for each sensor: [26.25935326 22.5854982  23.3329451 ]

Day with highest average temperature: 3

Z-score normalized data:
 [[ 0.30586474  0.46035726  1.06653852]
 [ 1.58796448  0.33227075  0.1079193 ]
 [ 1.65814966  1.67017008 -0.14791248]
 [ 0.3631366   0.02602452 -0.14384175]
 [-0.0123778  -1.91066995 -1.51268616]
 [-1.01706715 -0.70786984  0.70405961]
 [-1.44897006 -1.24147652  1.95573078]
 [-0.59668875  0.73525036 -1.18637625]
 [-0.99470001  0.79321562 -0.88878174]
 [ 0.1546883  -0.15727227  0.04535017]]

Correlation between sensors:
 [[ 1.          0.47376916 -0.17320705]
 [ 0.47376916  1.         -0.13444791]
 [-0.17320705 -0.13444791  1.        ]]
