# 10 - NumPy Exercise Solutions

## Introduction

This notebook contains complete solutions to all exercises from the previous notebook. Compare your solutions and learn different approaches.


In [1]:
import numpy as np


## Exercise 1: Array Creation - Solutions


In [2]:
# 1. Array of zeros
arr1 = np.zeros((3, 4))
print("1. Zeros (3x4):")
print(arr1)

# 2. Array of ones
arr2 = np.ones((2, 5))
print("\n2. Ones (2x5):")
print(arr2)

# 3. Array from 0 to 9
arr3 = np.arange(10)
print(f"\n3. Array 0-9: {arr3}")

# 4. Evenly spaced from 0 to 1
arr4 = np.linspace(0, 1, 10)
print(f"\n4. Linspace 0-1: {arr4}")

# 5. Identity matrix
arr5 = np.eye(3)
print("\n5. Identity matrix (3x3):")
print(arr5)


1. Zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2. Ones (2x5):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

3. Array 0-9: [0 1 2 3 4 5 6 7 8 9]

4. Linspace 0-1: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

5. Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Exercise 2: Array Operations - Solutions


In [3]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# 1. Elements > 40
result1 = arr[arr > 40]
print(f"1. Elements > 40: {result1}")

# 2. Elements between 30 and 60
result2 = arr[(arr >= 30) & (arr <= 60)]
print(f"2. Elements 30-60: {result2}")

# 3. Elements at indices 0, 2, 4, 6
result3 = arr[[0, 2, 4, 6]]
print(f"3. Elements at indices [0,2,4,6]: {result3}")

# 4. Reverse array
result4 = arr[::-1]
print(f"4. Reversed: {result4}")


1. Elements > 40: [50 60 70 80]
2. Elements 30-60: [30 40 50 60]
3. Elements at indices [0,2,4,6]: [10 30 50 70]
4. Reversed: [80 70 60 50 40 30 20 10]


## Exercise 3: Mathematical Operations - Solutions


In [4]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 1. Element-wise operations
print("1. Element-wise operations:")
print(f"Sum: {a + b}")
print(f"Difference: {b - a}")
print(f"Product: {a * b}")

# 2. Statistics of a
print(f"\n2. Statistics of a:")
print(f"Mean: {np.mean(a)}")
print(f"Std: {np.std(a)}")
print(f"Min: {np.min(a)}")
print(f"Max: {np.max(a)}")

# 3. Sum along axes
print(f"\n3. Sum along axes:")
print(f"Sum axis 0 (columns): {np.sum(arr2d, axis=0)}")
print(f"Sum axis 1 (rows): {np.sum(arr2d, axis=1)}")


1. Element-wise operations:
Sum: [11 22 33 44 55]
Difference: [ 9 18 27 36 45]
Product: [ 10  40  90 160 250]

2. Statistics of a:
Mean: 3.0
Std: 1.4142135623730951
Min: 1
Max: 5

3. Sum along axes:
Sum axis 0 (columns): [12 15 18]
Sum axis 1 (rows): [ 6 15 24]


## Exercise 4: Array Manipulation - Solutions


In [5]:
# 1. Reshape
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print("1. Reshaped to (3, 4):")
print(reshaped)

# 2. Flatten
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr2d.flatten()
print(f"\n2. Flattened: {flattened}")

# 3. Transpose
transposed = reshaped.T
print("\n3. Transposed:")
print(transposed)

# 4. Vertical stack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstacked = np.vstack([a, b])
print("\n4. Vertical stack:")
print(vstacked)


1. Reshaped to (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

2. Flattened: [1 2 3 4 5 6]

3. Transposed:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

4. Vertical stack:
[[1 2 3]
 [4 5 6]]


## Exercise 5: Data Processing - Solutions


In [6]:
np.random.seed(42)
data = np.random.normal(25, 5, (10, 3))
print("Sensor data:")
print(data)

# 1. Mean for each sensor
sensor_means = np.mean(data, axis=0)
print(f"\n1. Mean per sensor: {sensor_means}")

# 2. Day with highest average
daily_avg = np.mean(data, axis=1)
max_day = np.argmax(daily_avg)
print(f"\n2. Day with highest avg: Day {max_day} (temp: {daily_avg[max_day]:.2f})")

# 3. Z-score normalization
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
normalized = (data - mean) / std
print(f"\n3. Normalized data (first 3 rows):")
print(normalized[:3])

# 4. Correlation
correlation = np.corrcoef(data.T)
print(f"\n4. Correlation matrix:")
print(correlation)


Sensor data:
[[27.48357077 24.30867849 28.23844269]
 [32.61514928 23.82923313 23.82931522]
 [32.89606408 28.83717365 22.65262807]
 [27.71280022 22.68291154 22.67135123]
 [26.20981136 15.43359878 16.37541084]
 [22.18856235 19.9358444  26.57123666]
 [20.45987962 17.93848149 32.32824384]
 [23.8711185  25.33764102 17.87625907]
 [22.27808638 25.55461295 19.24503211]
 [26.87849009 21.99680655 23.54153125]]

1. Mean per sensor: [26.25935326 22.5854982  23.3329451 ]

2. Day with highest avg: Day 2 (temp: 28.13)

3. Normalized data (first 3 rows):
[[ 0.30586474  0.46035726  1.06653852]
 [ 1.58796448  0.33227075  0.1079193 ]
 [ 1.65814966  1.67017008 -0.14791248]]

4. Correlation matrix:
[[ 1.          0.47376916 -0.17320705]
 [ 0.47376916  1.         -0.13444791]
 [-0.17320705 -0.13444791  1.        ]]
